### PR TITLE
fix: improved branch cloning logic

### PR DESCRIPTION
**Pull request by gautamkrishnar**
improved branch cloning logic. It now checks if the branch exists and uses git cli's `--single-branch` to improve cloning speed.

### CODE REVIEW

**Comment by jgehrcke** [comment]
Lovely! As you've seen in the code comment above your change I actually wanted to do so. Thanks for tackling the special case. This is tested, I assume? :)

**Comment by gautamkrishnar** [comment]
> Lovely! As you've seen in the code comment above your change I actually wanted to do so. Thanks for tackling the special case. This is tested, I assume? :)

Yep, I am now doing more testing. Will let you know once I am done.

**Comment by gautamkrishnar** [comment]
@jgehrcke done testing, updated code to match the existing code style you are using.

**Comment by jgehrcke** [comment]
Lovely, thank you very much for this contribution! Please come back if you have more ideas :).

**Comment by flaix** [comment]
I might be doing something different than you did in your tests, but this code is not working in my install.
I am also not sure how it could work, because from how I read the code, a command is run under active `errexit` and then the [return code of said command is checked](https://github.com/jgehrcke/github-repo-stats/pull/32/files#diff-6f9d41d046756f0ddc2fcee0626bdb50100d12b88f293734eff742818e03efa2R45-R46). From my understanding this check will never be reached since the script will exit before it.
But again, I might be doing something different since you said you tested it and it worked for you.
I just wanted to let you know that I had to fix it (flaix/github-repo-stats@51c63536e9bbd9ed8d675c1483e9464876082352) to make it work.

**Comment by jgehrcke** [comment]
> @jgehrcke done testing

I should not have relied on only that but also should have reviewed a little more carefully. Anyway, we get that sorted out :) Thanks everyone!

**Comment by gautamkrishnar** [comment]
> I should not have relied on only that but also should have reviewed a little more carefully. Anyway, we get that sorted out :) Thanks everyone!

Really sorry for that. Yep, I never saw the `set +e` I only tested the part I had added. Glad to know that its fixed now.

**Pull request merged**
